/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import javax.swing.JOptionPane;
import Modelos.Classes.*;
import Modelos.Interface.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gusta
 */
public class TelaGrid extends javax.swing.JFrame {

    /**
     * Creates new form TelaGrid
     */
    public TelaGrid() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSegNumeroNatural = new javax.swing.JLabel();
        jLabelPrimNumeroNatural = new javax.swing.JLabel();
        jTextFieldPrimNumeroNatural = new javax.swing.JTextField();
        jTextFieldSegNumeroNatural = new javax.swing.JTextField();
        jButtonExecutar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNumeros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelSegNumeroNatural.setFont(new java.awt.Font("DialogInput", 3, 18)); // NOI18N
        jLabelSegNumeroNatural.setText("SEGUNDO NUMERO NATURAL");

        jLabelPrimNumeroNatural.setFont(new java.awt.Font("DialogInput", 3, 18)); // NOI18N
        jLabelPrimNumeroNatural.setText("PRIMEIRO NUMERO NATURAL");

        jButtonExecutar.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jButtonExecutar.setText("EXECUTAR");
        jButtonExecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExecutarActionPerformed(evt);
            }
        });

        jTableNumeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM", "Primeiro numero", "Segundo numero"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableNumeros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPrimNumeroNatural)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPrimNumeroNatural, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelSegNumeroNatural)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldSegNumeroNatural, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jButtonExecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonExecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrimNumeroNatural)
                            .addComponent(jTextFieldPrimNumeroNatural, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSegNumeroNatural)
                            .addComponent(jTextFieldSegNumeroNatural, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExecutarActionPerformed
        // TODO add your handling code here:
        try {
            int numero1 = Integer.parseInt(jTextFieldPrimNumeroNatural.getText());
            int numero2 = Integer.parseInt(jTextFieldSegNumeroNatural.getText());
            
            INNatural primeiro = new NNatural(numero1);
            INNatural segundo = new NNatural(numero2);
            
            DefaultTableModel model = (DefaultTableModel) jTableNumeros.getModel();
            String[] vetString = new String[3];
            
            vetString[0] = "QUADRADO PERFEITO";
            if(primeiro.eNumeroQuadradoPerfeito())
                vetString[1] = "SIM";
            else
                vetString[1] = "NÃO";
            if(segundo.eNumeroQuadradoPerfeito())
                vetString[2] = "SIM";
            else
                vetString[2] = "NÃO";
            
            model.addRow(vetString);
            
            vetString = new String[3];
            
            vetString[0] = "FATORIAL";
            vetString[1] = primeiro.calcularFatorial().getNumero()+"";
            vetString[2] = segundo.calcularFatorial().getNumero()+"";
            model.addRow(vetString);
            
            //////////////////////
            vetString = new String[3];
            
            vetString[0] = "NUMERO PERFEITO";
            if (primeiro.eNumeroPerfeito())
                vetString[1] = "SIM";
            else
                vetString[1] = "NÃO";
            if(segundo.eNumeroPerfeito())
                vetString[2] = "SIM";
            else
                vetString[2] = "NÃO";
            model.addRow(vetString);
            
            //////////////////////
            vetString = new String[3];
            
            vetString[0] = "Capicua";
            if (primeiro.eCapicua())
                vetString[1] = "SIM";
            else
                vetString[1] = "NÃO";
            if(segundo.eCapicua())
                vetString[2] = "SIM";
            else
                vetString[2] = "NÃO";
            model.addRow(vetString);
            //////////////////////
            vetString = new String[3];
            
            vetString[0] = "PRIMO";
            if (primeiro.ePrimo())
                vetString[1] = "SIM";
            else
                vetString[1] = "NÃO";
            if(segundo.ePrimo())
                vetString[2] = "SIM";
            else
                vetString[2] = "NÃO";
            model.addRow(vetString);
            //////////////////////
            vetString = new String[3];
            
            vetString[0] = "MDC";
            vetString[1] = primeiro.calcularMDC((NNatural) segundo).getNumero()+"";
            vetString[2] = segundo.calcularMDC((NNatural) primeiro).getNumero()+"";    
            model.addRow(vetString);
            //////////////////////
            vetString = new String[3];
            
            vetString[0] = "MMC";
            vetString[1] = primeiro.calcularMMC((NNatural) segundo).getNumero()+"";
            vetString[2] = segundo.calcularMMC((NNatural) primeiro).getNumero()+"";    
            model.addRow(vetString);
            //////////////////////
            vetString = new String[3];
            
            vetString[0] = "PRIMO ENTRE SI";
            if(primeiro.calcularMDC((NNatural) segundo).getNumero() == 1)
                vetString[1] = "SIM";
            else 
                vetString[1] = "NÃO";
            if(segundo.calcularMDC((NNatural) primeiro).getNumero() == 1)
                vetString[2] = "SIM";
            else 
                vetString[2] = "NÃO";
            model.addRow(vetString);
            //////////////////////
            vetString = new String[3];
            
            vetString[0] = "BASE 2";
            vetString[1] = primeiro.mudarBase(2)+"";
            vetString[2] = segundo.mudarBase(2)+"";   
            model.addRow(vetString);
            //////////////////////
            vetString = new String[3];
            
            vetString[0] = "BASE 8";
            vetString[1] = primeiro.mudarBase(8)+"";
            vetString[2] = segundo.mudarBase(8)+"";   
            model.addRow(vetString);
            //////////////////////
            vetString = new String[3];
            
            vetString[0] = "BASE 16";
            vetString[1] = primeiro.mudarBase(16)+"";
            vetString[2] = segundo.mudarBase(16)+"";   
            model.addRow(vetString);
            //////////////////////
            //Não colocar abaixo daqui!
            vetString = new String[3];
            model.addRow(vetString);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButtonExecutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGrid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGrid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGrid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGrid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGrid().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExecutar;
    private javax.swing.JLabel jLabelPrimNumeroNatural;
    private javax.swing.JLabel jLabelSegNumeroNatural;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNumeros;
    private javax.swing.JTextField jTextFieldPrimNumeroNatural;
    private javax.swing.JTextField jTextFieldSegNumeroNatural;
    // End of variables declaration//GEN-END:variables
}
